(() => {
  const en = {
    'О бренде':'About','Услуги':'Services','Прайс':'Prices','Салоны':'Salon','Контакты':'Contacts','ЗАГРУЗКА':'LOADING',
    'Записаться в WhatsApp ↗':'Book on WhatsApp ↗','Francesca · Пространство красоты':'Francesca · Beauty space',
    'Красота начинается с внимания к себе.':'Beauty begins with caring for yourself.',
    'Francesca — салон красоты в Новосибирске на Ядринцевской улице, 18. Здесь можно выбрать услуги для волос, макияжа, ногтей, лица и тела.':'Francesca is a beauty salon at 18 Yadrintsevskaya Street in Novosibirsk. Choose services for hair, makeup, nails, face and body.',
    'Расскажите, какой результат вы хотите получить. Состав услуги и стоимость можно уточнить у администратора перед записью.':'Tell us what result you would like. Our administrator will confirm the service details and price before your appointment.',
    'Наши услуги ↗':'Our services ↗','Пространство красоты':'Beauty space','Наверх ↑':'Back to top ↑','Мы в соцсетях':'Follow us',
    'Политика конфиденциальности':'Privacy policy','© 2026 FRANCESCA. ВСЕ ПРАВА ЗАЩИЩЕНЫ.':'© 2026 FRANCESCA. ALL RIGHTS RESERVED.','Разработчик':'Developer',
    'Будем на связи':'Let’s stay in touch','Напишите нам, чтобы выбрать услугу, уточнить стоимость и записаться.':'Message us to choose a service, confirm the price and book an appointment.',
    'Связаться с салоном':'Contact the salon','Открыть Telegram ↗':'Open Telegram ↗','Адрес':'Address','Новосибирск, Ядринцевская улица, 18':'18 Yadrintsevskaya Street, Novosibirsk','О салоне ↗':'About the salon ↗',
    'Красота,':'Beauty,','в которой':'where','вы — главное.':'you come first.','От естественного образа до особого события. Найдите время для себя в студии Francesca.':'From a natural everyday look to a special event. Make time for yourself at Francesca.','Francesca · ПРОСТРАНСТВО КРАСОТЫ · НОВОСИБИРСК · ЯДРИНЦЕВСКАЯ, 18 · Francesca · ПРОСТРАНСТВО КРАСОТЫ · НОВОСИБИРСК · ЯДРИНЦЕВСКАЯ, 18 ·':'Francesca · BEAUTY SPACE · NOVOSIBIRSK · 18 YADRINTSEVSKAYA STREET · Francesca · BEAUTY SPACE · NOVOSIBIRSK · 18 YADRINTSEVSKAYA STREET ·',
    'ОТКРОЙТЕ Francesca ↓':'DISCOVER Francesca ↓','Ваше пространство красоты':'Your beauty space','Внимание к вам. Красота в деталях.':'Care for you. Beauty in every detail.',
    'Быть собой.':'Be yourself.','Чувствовать себя':'Feel','прекрасно.':'beautiful.',
    'Макияж, волосы, уход за лицом и телом — в одном пространстве на Ядринцевской улице, 18 в Новосибирске.':'Makeup, hair, face and body care in one space at 18 Yadrintsevskaya Street in Novosibirsk.',
    'Выберите привычный уход или новый образ. Состав услуги и стоимость уточним вместе с вами перед записью.':'Choose your regular care or try a new look. We will confirm the service and price with you before booking.',
    'Больше о Francesca ↗':'More about Francesca ↗','Шесть направлений':'Six beauty areas','Красота начинается':'Beauty begins','с вашего желания.':'with what you want.','Все услуги ↗':'All services ↗',
    'Макияж и брови':'Makeup & brows','Естественные и выразительные образы.':'Natural and expressive looks.','Подробнее ↗':'Learn more ↗',
    'Парикмахерский зал':'Hair salon','Стрижки, укладки и забота о волосах.':'Haircuts, styling and hair care.','Ногтевой сервис':'Nail services','Маникюр, педикюр и аккуратные детали.':'Manicure, pedicure and polished details.',
    'Уход за лицом':'Facial care','Время для заботы о вашей коже.':'Time to care for your skin.','Уход за телом':'Body care','Расслабление и спа-ритуалы.':'Relaxation and spa rituals.','Эпиляция':'Hair removal','Гладкость и деликатный уход.':'Smooth skin and gentle care.',
    'Ждём вас':'We look forward to seeing you','До встречи в Francesca.':'See you at Francesca.','Как нас найти ↗':'Find us ↗','Мы рядом':'We are nearby','Как нас найти':'How to find us','Открыть большую карту ↗':'Open full map ↗',
    '— Прайс-лист · 6 направлений':'— Price list · 6 areas','Красота в деталях.':'Beauty in every detail.','Выберите направление и найдите уход, который подходит именно вам.':'Choose an area and find the care that is right for you.',
    'НАПРАВЛЕНИЯ':'CATEGORIES','Демонстрационный прайс.':'Sample price list.','Услуги и стоимость уточняйте при записи.':'Please confirm services and prices when booking.',
    'Ничего не найдено. Попробуйте другое название услуги.':'Nothing found. Try another service name.','Стоимость пока не указана. Перечень услуг и цены студии Francesca уточняйте при записи.':'Prices are being updated. Please confirm Francesca services and prices when booking.',
    'Ждём вас в Francesca':'We look forward to seeing you at Francesca','Где нас найти':'Where to find us','Открыть на карте ↗':'Open map ↗',
    'Правовая информация':'Legal information','Проект политики':'Draft policy','Перед публикацией необходимо указать оператора персональных данных, его реквизиты и контакт для обращений, адрес сайта, а также подтвердить, что описанные цели и способы обработки соответствуют работе салона.':'Before final publication, the personal-data controller, its details, contact information and website address must be specified, and the purposes and methods of processing must be confirmed.',
    'Francesca · Новосибирск':'Francesca · Novosibirsk','Francesca на Ядринцевской':'Francesca on Yadrintsevskaya Street','Время визита и подробности про вход уточняйте при записи.':'Please confirm your appointment time and entrance details when booking.',
    'Шесть направлений красоты':'Six beauty areas','Выберите уход для себя — от повседневного образа до подготовки к особому событию.':'Choose your care, from an everyday look to preparation for a special event.',
    'Макияж, оформление бровей и уход за ресницами.':'Makeup, brow shaping and lash care.','Услуги и цены ↗':'Services and prices ↗','Стрижки, укладки, окрашивание и уход за волосами.':'Haircuts, styling, colouring and hair care.',
    'Маникюр, педикюр, покрытие и уход за руками.':'Manicure, pedicure, polish and hand care.','Очищение, увлажнение и восстановление кожи.':'Skin cleansing, hydration and restoration.','Массаж и расслабляющие спа-ритуалы.':'Massage and relaxing spa rituals.','Услуги для гладкой и ухоженной кожи.':'Services for smooth, cared-for skin.',
    'Визаж · Брови · Ресницы':'Makeup · Brows · Lashes','Дневной макияж':'Day makeup','Вечерний макияж':'Evening makeup','Свадебный образ':'Bridal look','Коррекция и оформление бровей':'Brow shaping','Окрашивание бровей':'Brow tinting','Ламинирование ресниц':'Lash lift',
    'Стрижки · Укладки · Окрашивание':'Haircuts · Styling · Colouring','Женская стрижка с укладкой':'Women’s haircut with styling','Мужская стрижка':'Men’s haircut','Укладка волос':'Hair styling','Окрашивание в один тон':'Single-process colour','Сложное окрашивание':'Creative colour','Уход и восстановление волос':'Hair care and repair',
    'Маникюр · Педикюр · Уход':'Manicure · Pedicure · Care','Классический маникюр':'Classic manicure','Аппаратный маникюр':'E-file manicure','Покрытие гель-лаком':'Gel polish','Дизайн ногтей':'Nail art','Педикюр':'Pedicure','Уход за руками':'Hand care',
    'Очищение · Увлажнение · Восстановление':'Cleansing · Hydration · Repair','Консультация по уходу':'Skin-care consultation','Очищающий уход':'Cleansing treatment','Увлажняющий уход':'Hydrating treatment','Восстанавливающий уход':'Restorative treatment',
    'Массаж · Расслабление':'Massage · Relaxation','Расслабляющий массаж':'Relaxing massage','Массаж спины':'Back massage','Комплексный уход за телом':'Complete body treatment','Спа-ритуал':'Spa ritual','Гладкость · Деликатный уход':'Smoothness · Gentle care','Эпиляция ног':'Leg hair removal','Эпиляция рук':'Arm hair removal','Эпиляция подмышек':'Underarm hair removal','Эпиляция лица':'Facial hair removal',
    'Лёгкий образ в естественных оттенках на каждый день.':'A light everyday look in natural shades.','Обсуждение пожеланий и подбор оттенков':'Consultation and shade selection','Подготовка кожи: очищение и увлажнение':'Skin preparation: cleansing and hydration','Лёгкий тон и точечная коррекция':'Light foundation and targeted correction','Оформление бровей декоративной косметикой':'Brow makeup','Нейтральные тени и тушь':'Neutral eyeshadow and mascara','Румяна, макияж губ и фиксация':'Blush, lip makeup and setting',
    'Выразительный макияж для вечернего события.':'Expressive makeup for an evening event.','Подготовка кожи и выравнивание тона':'Skin preparation and an even complexion','Оформление бровей и макияж глаз':'Brow shaping and eye makeup','Акценты на скулах и губах':'Cheekbone and lip accents','Фиксация образа':'Makeup setting',
    'Макияж с учётом платья, причёски и пожеланий невесты.':'Makeup tailored to the dress, hairstyle and bride’s wishes.','Обсуждение образа и оттенков':'Look and shade consultation','Подготовка кожи':'Skin preparation','Создание и фиксация макияжа':'Makeup application and setting',
    'Аккуратная форма бровей с учётом черт лица.':'A neat brow shape suited to your facial features.','Подбор формы':'Shape selection','Коррекция лишних волосков':'Hair removal and shaping','Завершающий уход':'Finishing care','Окрашивание бровей в подходящий оттенок.':'Brow tinting in a suitable shade.','Выбор оттенка и насыщенности':'Shade and intensity selection','Подготовка и окрашивание':'Preparation and tinting','Выразительный изгиб и ухоженный вид ресниц.':'A defined curl and a polished lash look.','Обсуждение результата':'Result consultation','Проведение процедуры':'Treatment','Рекомендации по уходу':'Aftercare advice',
    'от 5 000 ₽':'from 5,000 ₽','По запросу':'On request','Уточняется':'To be confirmed','Пример состава услуги. Точный состав и итоговую стоимость уточняйте при записи.':'Sample service details. Please confirm the exact service and final price when booking.','Состав услуги и итоговую стоимость мастер согласует с вами перед началом. Напишите нам в WhatsApp, чтобы уточнить подробности и выбрать время.':'Your specialist will confirm the service and final price before starting. Message us on WhatsApp for details and available times.'
  };

  const es = {
    'О бренде':'La marca','Услуги':'Servicios','Прайс':'Precios','Салоны':'Salón','Контакты':'Contactos','ЗАГРУЗКА':'CARGANDO','Записаться в WhatsApp ↗':'Reservar por WhatsApp ↗','Francesca · Пространство красоты':'Francesca · Espacio de belleza',
    'Красота начинается с внимания к себе.':'La belleza comienza al cuidarte.','Francesca — салон красоты в Новосибирске на Ядринцевской улице, 18. Здесь можно выбрать услуги для волос, макияжа, ногтей, лица и тела.':'Francesca es un salón de belleza en la calle Yadrintsevskaya 18, Novosibirsk. Ofrecemos servicios de cabello, maquillaje, uñas, rostro y cuerpo.','Расскажите, какой результат вы хотите получить. Состав услуги и стоимость можно уточнить у администратора перед записью.':'Cuéntanos qué resultado deseas. Nuestro administrador confirmará los detalles y el precio antes de la cita.',
    'Наши услуги ↗':'Nuestros servicios ↗','Пространство красоты':'Espacio de belleza','Наверх ↑':'Volver arriba ↑','Мы в соцсетях':'Síguenos','Политика конфиденциальности':'Política de privacidad','© 2026 FRANCESCA. ВСЕ ПРАВА ЗАЩИЩЕНЫ.':'© 2026 FRANCESCA. TODOS LOS DERECHOS RESERVADOS.','Разработчик':'Desarrollador',
    'Будем на связи':'Hablemos','Напишите нам, чтобы выбрать услугу, уточнить стоимость и записаться.':'Escríbenos para elegir un servicio, confirmar el precio y reservar una cita.','Связаться с салоном':'Contactar con el salón','Открыть Telegram ↗':'Abrir Telegram ↗','Адрес':'Dirección','Новосибирск, Ядринцевская улица, 18':'Calle Yadrintsevskaya 18, Novosibirsk','О салоне ↗':'Sobre el salón ↗',
    'Красота,':'Belleza,','в которой':'donde','вы — главное.':'tú eres lo primero.','От естественного образа до особого события. Найдите время для себя в студии Francesca.':'Desde un look natural hasta un evento especial. Dedícate tiempo en Francesca.','Francesca · ПРОСТРАНСТВО КРАСОТЫ · НОВОСИБИРСК · ЯДРИНЦЕВСКАЯ, 18 · Francesca · ПРОСТРАНСТВО КРАСОТЫ · НОВОСИБИРСК · ЯДРИНЦЕВСКАЯ, 18 ·':'Francesca · ESPACIO DE BELLEZA · NOVOSIBIRSK · CALLE YADRINTSEVSKAYA 18 · Francesca · ESPACIO DE BELLEZA · NOVOSIBIRSK · CALLE YADRINTSEVSKAYA 18 ·','ОТКРОЙТЕ Francesca ↓':'DESCUBRE Francesca ↓','Ваше пространство красоты':'Tu espacio de belleza','Внимание к вам. Красота в деталях.':'Atención para ti. Belleza en cada detalle.','Быть собой.':'Sé tú misma.','Чувствовать себя':'Siéntete','прекрасно.':'radiante.',
    'Макияж, волосы, уход за лицом и телом — в одном пространстве на Ядринцевской улице, 18 в Новосибирске.':'Maquillaje, cabello y cuidado facial y corporal en un solo espacio en la calle Yadrintsevskaya 18, Novosibirsk.','Выберите привычный уход или новый образ. Состав услуги и стоимость уточним вместе с вами перед записью.':'Elige tu cuidado habitual o prueba un nuevo look. Confirmaremos el servicio y el precio antes de reservar.','Больше о Francesca ↗':'Más sobre Francesca ↗','Шесть направлений':'Seis áreas de belleza','Красота начинается':'La belleza comienza','с вашего желания.':'con lo que deseas.','Все услуги ↗':'Todos los servicios ↗',
    'Макияж и брови':'Maquillaje y cejas','Естественные и выразительные образы.':'Looks naturales y expresivos.','Подробнее ↗':'Más información ↗','Парикмахерский зал':'Peluquería','Стрижки, укладки и забота о волосах.':'Cortes, peinados y cuidado del cabello.','Ногтевой сервис':'Uñas','Маникюр, педикюр и аккуратные детали.':'Manicura, pedicura y detalles impecables.','Уход за лицом':'Cuidado facial','Время для заботы о вашей коже.':'Tiempo para cuidar tu piel.','Уход за телом':'Cuidado corporal','Расслабление и спа-ритуалы.':'Relajación y rituales de spa.','Эпиляция':'Depilación','Гладкость и деликатный уход.':'Piel suave y cuidado delicado.',
    'Ждём вас':'Te esperamos','До встречи в Francesca.':'Nos vemos en Francesca.','Как нас найти ↗':'Cómo llegar ↗','Мы рядом':'Estamos cerca','Как нас найти':'Cómo encontrarnos','Открыть большую карту ↗':'Abrir mapa completo ↗','— Прайс-лист · 6 направлений':'— Lista de precios · 6 áreas','Красота в деталях.':'Belleza en cada detalle.','Выберите направление и найдите уход, который подходит именно вам.':'Elige un área y encuentra el cuidado ideal para ti.','НАПРАВЛЕНИЯ':'CATEGORÍAS','Демонстрационный прайс.':'Lista de precios de muestra.','Услуги и стоимость уточняйте при записи.':'Confirma los servicios y precios al reservar.','Ничего не найдено. Попробуйте другое название услуги.':'No se encontró nada. Prueba otro nombre de servicio.','Стоимость пока не указана. Перечень услуг и цены студии Francesca уточняйте при записи.':'Los precios se están actualizando. Confirma los servicios y precios al reservar.','Ждём вас в Francesca':'Te esperamos en Francesca','Где нас найти':'Dónde encontrarnos','Открыть на карте ↗':'Abrir mapa ↗',
    'Правовая информация':'Información legal','Проект политики':'Borrador de política','Перед публикацией необходимо указать оператора персональных данных, его реквизиты и контакт для обращений, адрес сайта, а также подтвердить, что описанные цели и способы обработки соответствуют работе салона.':'Antes de la publicación final deben indicarse el responsable de datos, sus datos de contacto y la dirección del sitio, y confirmarse las finalidades y métodos de tratamiento.','Francesca · Новосибирск':'Francesca · Novosibirsk','Francesca на Ядринцевской':'Francesca en la calle Yadrintsevskaya','Время визита и подробности про вход уточняйте при записи.':'Confirma la hora de la cita y los detalles de acceso al reservar.',
    'Шесть направлений красоты':'Seis áreas de belleza','Выберите уход для себя — от повседневного образа до подготовки к особому событию.':'Elige tu cuidado, desde un look diario hasta la preparación para un evento especial.','Макияж, оформление бровей и уход за ресницами.':'Maquillaje, diseño de cejas y cuidado de pestañas.','Услуги и цены ↗':'Servicios y precios ↗','Стрижки, укладки, окрашивание и уход за волосами.':'Cortes, peinados, coloración y cuidado del cabello.','Маникюр, педикюр, покрытие и уход за руками.':'Manicura, pedicura, esmaltado y cuidado de manos.','Очищение, увлажнение и восстановление кожи.':'Limpieza, hidratación y recuperación de la piel.','Массаж и расслабляющие спа-ритуалы.':'Masajes y rituales de spa relajantes.','Услуги для гладкой и ухоженной кожи.':'Servicios para una piel suave y cuidada.',
    'Визаж · Брови · Ресницы':'Maquillaje · Cejas · Pestañas','Дневной макияж':'Maquillaje de día','Вечерний макияж':'Maquillaje de noche','Свадебный образ':'Look de novia','Коррекция и оформление бровей':'Diseño de cejas','Окрашивание бровей':'Tinte de cejas','Ламинирование ресниц':'Lifting de pestañas','Стрижки · Укладки · Окрашивание':'Cortes · Peinados · Coloración','Женская стрижка с укладкой':'Corte femenino con peinado','Мужская стрижка':'Corte masculino','Укладка волос':'Peinado','Окрашивание в один тон':'Coloración de un tono','Сложное окрашивание':'Coloración creativa','Уход и восстановление волос':'Cuidado y reparación capilar','Маникюр · Педикюр · Уход':'Manicura · Pedicura · Cuidado','Классический маникюр':'Manicura clásica','Аппаратный маникюр':'Manicura con torno','Покрытие гель-лаком':'Esmaltado semipermanente','Дизайн ногтей':'Diseño de uñas','Педикюр':'Pedicura','Уход за руками':'Cuidado de manos','Очищение · Увлажнение · Восстановление':'Limpieza · Hidratación · Recuperación','Консультация по уходу':'Consulta de cuidado facial','Очищающий уход':'Tratamiento de limpieza','Увлажняющий уход':'Tratamiento hidratante','Восстанавливающий уход':'Tratamiento reparador','Массаж · Расслабление':'Masaje · Relajación','Расслабляющий массаж':'Masaje relajante','Массаж спины':'Masaje de espalda','Комплексный уход за телом':'Tratamiento corporal completo','Спа-ритуал':'Ritual de spa','Гладкость · Деликатный уход':'Suavidad · Cuidado delicado','Эпиляция ног':'Depilación de piernas','Эпиляция рук':'Depilación de brazos','Эпиляция подмышек':'Depilación de axilas','Эпиляция лица':'Depilación facial',
    'Лёгкий образ в естественных оттенках на каждый день.':'Un look diario ligero en tonos naturales.','Обсуждение пожеланий и подбор оттенков':'Consulta y selección de tonos','Подготовка кожи: очищение и увлажнение':'Preparación de la piel: limpieza e hidratación','Лёгкий тон и точечная коррекция':'Base ligera y corrección localizada','Оформление бровей декоративной косметикой':'Maquillaje de cejas','Нейтральные тени и тушь':'Sombras neutras y máscara','Румяна, макияж губ и фиксация':'Colorete, maquillaje de labios y fijación','Выразительный макияж для вечернего события.':'Maquillaje expresivo para un evento nocturno.','Подготовка кожи и выравнивание тона':'Preparación de la piel y tono uniforme','Оформление бровей и макияж глаз':'Diseño de cejas y maquillaje de ojos','Акценты на скулах и губах':'Acentos en pómulos y labios','Фиксация образа':'Fijación del maquillaje','Макияж с учётом платья, причёски и пожеланий невесты.':'Maquillaje adaptado al vestido, peinado y deseos de la novia.','Обсуждение образа и оттенков':'Consulta del look y los tonos','Подготовка кожи':'Preparación de la piel','Создание и фиксация макияжа':'Aplicación y fijación del maquillaje','Аккуратная форма бровей с учётом черт лица.':'Forma de cejas adaptada a tus rasgos.','Подбор формы':'Selección de la forma','Коррекция лишних волосков':'Depilación y diseño','Завершающий уход':'Cuidado final','Окрашивание бровей в подходящий оттенок.':'Tinte de cejas en un tono adecuado.','Выбор оттенка и насыщенности':'Selección del tono y la intensidad','Подготовка и окрашивание':'Preparación y tinte','Выразительный изгиб и ухоженный вид ресниц.':'Curvatura definida y pestañas cuidadas.','Обсуждение результата':'Consulta sobre el resultado','Проведение процедуры':'Tratamiento','Рекомендации по уходу':'Consejos de cuidado','от 5 000 ₽':'desde 5.000 ₽','По запросу':'A consultar','Уточняется':'Por confirmar','Пример состава услуги. Точный состав и итоговую стоимость уточняйте при записи.':'Ejemplo del servicio. Confirma los detalles exactos y el precio final al reservar.','Состав услуги и итоговую стоимость мастер согласует с вами перед началом. Напишите нам в WhatsApp, чтобы уточнить подробности и выбрать время.':'Tu especialista confirmará el servicio y el precio final antes de comenzar. Escríbenos por WhatsApp para conocer los detalles y horarios disponibles.'
  };

  const titles = {
    en: {'Francesca — О бренде':'Francesca — About','Francesca — Контакты':'Francesca — Contacts','Francesca — Пространство красоты в Новосибирске':'Francesca — Beauty space in Novosibirsk','Francesca — Прайс-лист':'Francesca — Price list','Francesca — Политика конфиденциальности':'Francesca — Privacy policy','Francesca — Салоны':'Francesca — Salon','Francesca — Услуги':'Francesca — Services'},
    es: {'Francesca — О бренде':'Francesca — La marca','Francesca — Контакты':'Francesca — Contactos','Francesca — Пространство красоты в Новосибирске':'Francesca — Espacio de belleza en Novosibirsk','Francesca — Прайс-лист':'Francesca — Lista de precios','Francesca — Политика конфиденциальности':'Francesca — Política de privacidad','Francesca — Салоны':'Francesca — Salón','Francesca — Услуги':'Francesca — Servicios'}
  };

  const attributes = {
    en: {'Основная навигация':'Main navigation','Навигация внизу страницы':'Footer navigation','Francesca — главная страница':'Francesca — home page','Поиск по услугам':'Search services','Поиск по услугам…':'Search services…','Очистить поиск':'Clear search','Разработчик — открыть Telegram':'Developer — open Telegram','ВКонтакте':'VK','Карта: салон Francesca, Новосибирск, Ядринцевская улица, 18':'Map: Francesca salon, 18 Yadrintsevskaya Street, Novosibirsk'},
    es: {'Основная навигация':'Navegación principal','Навигация внизу страницы':'Navegación del pie','Francesca — главная страница':'Francesca — página principal','Поиск по услугам':'Buscar servicios','Поиск по услугам…':'Buscar servicios…','Очистить поиск':'Borrar búsqueda','Разработчик — открыть Telegram':'Desarrollador — abrir Telegram','ВКонтакте':'VK','Карта: салон Francesca, Новосибирск, Ядринцевская улица, 18':'Mapa: salón Francesca, calle Yadrintsevskaya 18, Novosibirsk'}
  };

  const privacy = {
    en: `<h2>1. General provisions</h2><p>This personal data processing policy is prepared in accordance with Federal Law No. 152-FZ “On Personal Data” and describes how the Controller processes and protects personal data.</p><p>The Controller’s priority is to respect human and civil rights when processing personal data, including privacy and family confidentiality. This policy applies to information the Controller may receive from visitors to the Francesca website.</p><h2>2. Key terms</h2><p>Personal data means information relating directly or indirectly to an identified or identifiable website user. Processing includes collection, recording, storage, updating, use, transfer, anonymisation, blocking, deletion and destruction of data, with or without automation.</p><p>The Controller is the person or organisation that determines the purposes, content and methods of personal data processing. A user is any visitor to the Francesca website.</p><h2>3. Rights and duties of the Controller</h2><p>The Controller may request accurate information and documents and may continue processing where permitted by law after consent is withdrawn. The Controller must answer lawful requests, publish this policy, protect personal data and stop processing or delete data when required by law.</p><h2>4. Rights and duties of data subjects</h2><p>Data subjects may obtain information about processing, request correction, blocking or deletion of inaccurate or unlawfully obtained data, withdraw consent and appeal unlawful actions. They must provide accurate data and report updates.</p><h2>5. Processing principles</h2><p>Data is processed lawfully and fairly, only for specific and legitimate purposes. The amount of data must match those purposes, remain accurate and be stored no longer than necessary.</p><h2>6. Processing purposes</h2><ul><li>booking services at Francesca;</li><li>providing information about offers, promotions and news;</li><li>responding to enquiries;</li><li>improving service quality and the website.</li></ul><h2>7. Processing conditions</h2><p>Data is processed with the data subject’s consent or on another legal basis, including where processing is required by law or necessary to perform or enter into a contract.</p><h2>8. Confidentiality</h2><p>The Controller and other persons with access to personal data must not disclose or distribute it without the data subject’s consent unless required by federal law.</p><h2>9. Final provisions</h2><p>Users may request clarification about personal data processing through the website’s contact channels. Changes will be reflected in this document. The policy remains in force until replaced by a new version.</p>`,
    es: `<h2>1. Disposiciones generales</h2><p>Esta política de tratamiento de datos personales se ha elaborado de conformidad con la Ley Federal n.º 152-FZ «Sobre datos personales» y describe cómo el Responsable trata y protege los datos personales.</p><p>La prioridad del Responsable es respetar los derechos y libertades de las personas, incluida la privacidad y la confidencialidad familiar. Esta política se aplica a la información recibida de los visitantes del sitio web de Francesca.</p><h2>2. Términos principales</h2><p>Los datos personales son la información relacionada directa o indirectamente con un usuario identificado o identificable. El tratamiento incluye la recopilación, registro, almacenamiento, actualización, uso, transferencia, anonimización, bloqueo, eliminación y destrucción de datos, con o sin medios automatizados.</p><p>El Responsable es la persona u organización que determina las finalidades, el contenido y los métodos del tratamiento. Usuario es cualquier visitante del sitio web de Francesca.</p><h2>3. Derechos y obligaciones del Responsable</h2><p>El Responsable puede solicitar información y documentos exactos y continuar el tratamiento después de retirar el consentimiento cuando la ley lo permita. Debe responder a solicitudes legales, publicar esta política, proteger los datos y detener el tratamiento o eliminar los datos cuando lo exija la ley.</p><h2>4. Derechos y obligaciones de los interesados</h2><p>Los interesados pueden obtener información, solicitar la corrección, bloqueo o eliminación de datos inexactos o obtenidos ilegalmente, retirar el consentimiento y recurrir las acciones ilegales. Deben proporcionar datos exactos y comunicar cualquier actualización.</p><h2>5. Principios del tratamiento</h2><p>Los datos se tratan de forma lícita y leal, únicamente para fines específicos y legítimos. La cantidad de datos debe corresponder a esos fines, mantenerse exacta y conservarse solo durante el tiempo necesario.</p><h2>6. Finalidades del tratamiento</h2><ul><li>reservar servicios en Francesca;</li><li>informar sobre ofertas, promociones y novedades;</li><li>responder a consultas;</li><li>mejorar la calidad del servicio y del sitio web.</li></ul><h2>7. Condiciones del tratamiento</h2><p>Los datos se tratan con el consentimiento del interesado o sobre otra base legal, incluso cuando el tratamiento sea exigido por la ley o necesario para ejecutar o celebrar un contrato.</p><h2>8. Confidencialidad</h2><p>El Responsable y otras personas con acceso a los datos personales no deben revelarlos ni distribuirlos sin el consentimiento del interesado, salvo obligación legal.</p><h2>9. Disposiciones finales</h2><p>Los usuarios pueden solicitar aclaraciones sobre el tratamiento mediante los canales de contacto del sitio. Los cambios se reflejarán en este documento. La política permanecerá vigente hasta que sea sustituida por una nueva versión.</p>`
  };

  const originalText = new WeakMap();
  const originalAttrs = new WeakMap();
  let privacyOriginal = null;

  function rememberAttribute(element, name) {
    let saved = originalAttrs.get(element);
    if (!saved) { saved = {}; originalAttrs.set(element, saved); }
    if (!(name in saved)) saved[name] = element.getAttribute(name);
    return saved[name];
  }

  function translateTree(lang) {
    const dictionary = lang === 'en' ? en : lang === 'es' ? es : null;
    const article = document.querySelector('.privacy-page article');
    if (article) {
      if (privacyOriginal === null) privacyOriginal = article.innerHTML;
      article.innerHTML = lang === 'ru' ? privacyOriginal : privacy[lang];
    }
    const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
    let node;
    while ((node = walker.nextNode())) {
      if (!originalText.has(node)) originalText.set(node, node.nodeValue);
      const original = originalText.get(node);
      const trimmed = original.trim();
      if (!trimmed) continue;
      const translated = dictionary && dictionary[trimmed];
      node.nodeValue = translated ? original.replace(trimmed, translated) : original;
    }
    document.querySelectorAll('[aria-label],[title],[placeholder],[alt]').forEach(element => {
      ['aria-label','title','placeholder','alt'].forEach(name => {
        if (!element.hasAttribute(name)) return;
        const original = rememberAttribute(element, name);
        element.setAttribute(name, (attributes[lang] && attributes[lang][original]) || original);
      });
    });
  }

  function applyLanguage(lang) {
    if (!['en','ru','es'].includes(lang)) lang = 'en';
    translateTree(lang);
    const originalTitle = document.documentElement.dataset.originalTitle || document.title;
    document.documentElement.dataset.originalTitle = originalTitle;
    document.title = (titles[lang] && titles[lang][originalTitle]) || originalTitle;
    document.documentElement.lang = lang;
    document.querySelectorAll('.language-select').forEach(select => { select.value = lang; });
    document.querySelectorAll('.language-switcher-label').forEach(label => { label.textContent = lang === 'ru' ? 'Язык' : lang === 'es' ? 'Idioma' : 'Language'; });
    try { localStorage.setItem('francesca-language', lang); } catch (_) {}
    document.dispatchEvent(new CustomEvent('francesca:language', { detail: { lang } }));
  }

  function start() {
    document.querySelectorAll('a.booking[href*="wa.me"]').forEach(link => {
      const pair = document.createElement('div');
      pair.className = 'booking-pair';
      link.before(pair); pair.append(link);
      const facebook = document.createElement('a');
      facebook.className = 'booking facebook-booking';
      facebook.href = 'https://www.facebook.com/login/';
      facebook.target = '_blank'; facebook.rel = 'noopener noreferrer';
      pair.append(facebook);
    });
    const updateFacebook = lang => document.querySelectorAll('.facebook-booking').forEach(link => { link.textContent = lang === 'ru' ? 'Записаться в Facebook ↗' : lang === 'es' ? 'Reservar en Facebook ↗' : 'Book on Facebook ↗'; });
    document.addEventListener('francesca:language', event => updateFacebook(event.detail.lang));
    document.querySelectorAll('.language-select').forEach(select => select.addEventListener('change', event => applyLanguage(event.target.value)));
    let saved = 'en';
    try { saved = localStorage.getItem('francesca-language') || 'en'; } catch (_) {}
    applyLanguage(saved);
  }

  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', start, { once: true });
  else start();
})();
